### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by kouassikadijar2212** [swagkarna/EvilJack#6]
Hey man 
For telegram I don't know how to use it
I just get a Qrcode from telegram and when I can it , it shows authentication fail

**Comment by bitosalpha** [comment]
Can you describe it in more details? Probably you are not scanning from Telegram official app.

**Comment by kouassikadijar2212** [comment]
Yes for sure.
Look when you scan QRcode Whatsapp it says this:
When your phone reads the QR code, it contacts the WhatsApp servers with
the information required to ensure a secure connection. Your phone tells
the WhatsApp servers my number is XXXX, my authentication credentials are
YYYY, and the WebSocket associated with the QR code I just scanned can now
receive my data.
In telegram it is not the same each time you want to login your qrcode must
be updated.
